### ISSUE TITLE
Why the classifiers are the same in adaboost?

### ISSUE THREAD

**Issue by whcn** [eriklindernoren/ML-From-Scratch#17]
I have following questions about adaboost implementation

- Why the classifiers are the same in the end?
- Why concatenate y_pred in `predict` function?

Though the accuracy of classification has no problem,  I think the implementation is wrong.

**Comment by eriklindernoren** [comment]
- I decided to implement the Adaboost algorithm with decision stumps (one-level decision tree) since this version of Adaboost tends to perform well out-of-the-box. This is from the Wikipedia page of Adaboost: "While every learning algorithm will tend to suit some problem types better than others, and will typically have many different parameters and configurations to be adjusted before achieving optimal performance on a dataset, AdaBoost (with decision trees as the weak learners) is often referred to as the best out-of-the-box classifier." The classifiers will however not be "the same" as they will classify samples based on different feature values and different threshold values. The classifiers that are more accurate on the training data will have greater impact on the final prediction of the test sample (more accurate => higher alpha value). 
- The reason that y_pred is concatenated in predict is so that the classifier's prediction are of y are added as columns (so column i represents the predictions of y for classifier i). These columns are weighted by the classifier's alpha value, which like i described in my answer to your first questions represents how much impact this classifier will have on the final prediction of y. These columns are then summed, and y is then classified as the sign value.
From Wikipedia: "For example in the two class problem, the sign of the weak learner output identifies the predicted object class and the absolute value gives the confidence in that classification. Similarly, the {\displaystyle T} Tth classifier will be positive if the sample is believed to be in the positive class and negative otherwise."

Hope this answers your questions.

**Comment by whcn** [comment]
In line 95, `w = w.dot(np.exp(clf.alpha * y.dot(predictions)))`. I think this line of code is plan to update weight of data points. In theory, we assign smaller values to hit points, and higher values to miss points. But `np.exp(clf.alpha * y.dot(predictions))` is scalar, i.e. **numpy.float64**, it means that all weights still be same after updating.

**Comment by eriklindernoren** [comment]
Ah, you're right. w is never assigned higher values for misclassified samples and lower for correctly classified samples. The problem was not using np.exp (which calculates the exponential of all elements in the input array and returns the resulting array) however, but the exponent. The problem was that I calculated the dot product instead of doing vector multiplication. 
Changing it to the following line fixed this issue: 
`w *= np.exp(-clf.alpha * y * predictions)`

Thank you for pointing this out. This is resolved in the latest commit.

**Comment by hisabness** [comment]
I can't seem to unsubscribe or mute this thread. Any thoughts?

**Comment by eriklindernoren** [comment]
@hisabness you can change notification preferences for repositories that you're watching in Personal Settings -> Notifications.

Some additional information here:
https://help.github.com/articles/about-notifications/
